# Data sources

```{r, read data}
# NY_Jan = read.csv("~/Desktop/NY_Jan.csv") #2021
# Jan_19 = read.csv('~/Desktop/19Jan.csv')
# 
# 
# f1901 <- read.csv('./datasets/2019_01.csv')
# f1902 <- read.csv('./datasets/2019_02.csv')
# f1903 <- read.csv('./datasets/2019_03.csv')
# f1904 <- read.csv('./datasets/2019_04.csv')
# f1905 <- read.csv('./datasets/2019_05.csv')
# f1906 <- read.csv('./datasets/2019_06.csv')
# f1907 <- read.csv('./datasets/2019_07.csv')
# f1908 <- read.csv('./datasets/2019_08.csv')
# f1909 <- read.csv('./datasets/2019_09.csv')
# f1910 <- read.csv('./datasets/2019_10.csv')
# f1911 <- read.csv('./datasets/2019_11.csv')
# f1912 <- read.csv('./datasets/2019_12.csv')
# 
# NY_2019 <- rbind(f1901, f1902, f1903, f1904, f1905, f1906,
#                  f1907, f1908, f1909, f1910, f1911, f1912)
# 
# f2001 <- read.csv('./datasets/2020_01.csv')
# f2002 <- read.csv('./datasets/2020_02.csv')
# f2003 <- read.csv('./datasets/2020_03.csv')
# f2004 <- read.csv('./datasets/2020_04.csv')
# f2005 <- read.csv('./datasets/2020_05.csv')
# f2006 <- read.csv('./datasets/2020_06.csv')
# f2007 <- read.csv('./datasets/2020_07.csv')
# f2008 <- read.csv('./datasets/2020_08.csv')
# f2009 <- read.csv('./datasets/2020_09.csv')
# f2010 <- read.csv('./datasets/2020_10.csv')
# f2011 <- read.csv('./datasets/2020_11.csv')
# f2012 <- read.csv('./datasets/2020_12.csv')
# 
# NY_2020 <- rbind(f2001, f2002, f2003, f2004, f2005, f2006,
#                  f2007, f2008, f2009, f2010, f2011, f2012)

# f2101 <- read.csv('./datasets/2021_01.csv')
# f2102 <- read.csv('./datasets/2021_02.csv')
# f2103 <- read.csv('./datasets/2021_03.csv')
# f2104 <- read.csv('./datasets/2021_04.csv')
# f2105 <- read.csv('./datasets/2021_05.csv')
# f2106 <- read.csv('./datasets/2021_06.csv')
# f2107 <- read.csv('./datasets/2021_07.csv')
# f2108 <- read.csv('./datasets/2021_08.csv')
# 
# NY_2021 <- rbind(f2101, f2102, f2103, f2104, f2105, f2106,
#                  f2107, f2108)

# NY_dec <- rbind(f1912, f2012)




for (i in formatC(c(1:12), width=2, flag="0")) {
  varname = paste('a19',i, sep='' )
  filename = paste('./datasets/a19', i,'.csv', sep='')
  assign(varname, read.csv(filename))
}

US_2019 <- rbind(a1901, a1902, a1903, a1904, a1905, a1906, a1907,
                 a1908, a1909, a1910, a1911, a1912)


for (i in formatC(c(1:12), width=2, flag="0")) {
  varname = paste('a20',i, sep='' )
  filename = paste('./datasets/a20', i,'.csv', sep='')
  assign(varname, read.csv(filename))
}

US_2020 <- rbind(a2001, a2002, a2003, a2004, a2005, a2006,
                 a2007, a2008, a2009, a2010, a2011, a2012)

airline_ID <- read.csv('./datasets/L_AIRLINE_ID.csv')


```


We collect the data from the Bureau of Transportation Statistics. Ziyan Liu is in charge of pulling the datasets down from the website. Since we want to analyze flight delays, we select the "Aviation" mode in the data finder, find the database called "Airline On-Time Performance Data", and download tables from "Marketing Carrier On-Time Performance (Beginning January 2018)" (https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FGK&QO_fu146_anzr=b0-gvzr). 

It is nice that the website provides field selection feature, and we select 29 variables that we find useful in our project to include in the datasets. These variables include information about airline carriers, origins, destinations, departure and arrival time and delay situations of U.S. domestic flights. We download 24 tables in total, each containing flight information during one month from January 2019 to December 2020.


'YEAR', 'DAY_OF_WEEK', 'FL_DATE' are the three variables that indicate the date of flights.  'MKT_CARRIER_AIRLINE_ID' is the identification number assigned by US DOT to identify a unique airline (carrier). 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR' are the abbreviation of origin airport, origin city name, and the abbreviation of origin state. 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR' contain information similarly for the destination. 'CRS_DEP_TIME' is the CRS departure time of flight, 'DEP_TIME' is the actual departure time, 'DEP_DELAY' is the departure delay time in minutes, where negative numbers indicate early departure, and 'DEP_DELAY_NEW' is the same with 'DEP_DELAY' except negative numbers are replaced by 0. Arrival information are encoded in the 'ARR' variables similarly. 'CANCELLED' indicates if the flight is cancelled, where 1 means it is, and 'CANCELLATION_CODE' specifies reasons for cancellation. 'CRS_ELAPSED_TIME' is the estimated elapsed time of flight in minutes, 'ACTUAL_ELAPSED_TIME' is the actual time, and 'AIR_TIME' is the flight time. 'DISTANCE' gives the distance between airports in miles. Lastly, 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY' and 'LLATE_AIRCRAFT_DELAY' are the causes of delay in minutes.  

The datasets before March 2020 contain about 650,000 records per month, and there is a significant drop after March 2020, obviously due to the pandemic, where each contains about  350,000 records. In total, there are 8,066,815 and 5,022,397 records of U.S. domestic flights respectively in 2019 and 2020.


The datasets contain very detailed information and statistics. We found that, however, there are flights that did not fly and are NA's in the tables, and that some flights are delayed, but no specific reasons are given. 
 <!-- It causes some mismatch when we analyze the reasons that cause flight delays. -->










