# Conclusion
<!-- Limitation and Future Direction, Lessons Learned -->
In this project, we created visualizations of data by exploratory data analysis, and made it easier for the audience to see the differences among airline carriers, flight departure time, etc. However, we were not able to analyze all variables that might affect on-time performance. For instance, we haven't got a chance to see if the day of week influences the flight performance. It could be possible that Sunday flights are more likely to delay than the ones on Wednesday. In future exploration, we can certainly look for more trends similar to this, and make more interesting plots based on the data.  

During the progress of analyzing the dataset, we both gained a better understanding of what we have learned during the semester. We utilized `dplyr`, `ggplot2`, and many other useful R packages that we learned from the course to make a variety of graphs, such as bar plot, scatterplot and heatmap, in the results section. The strategies to interpret and handle `NA` values were also useful to deal with missing values. Further, when creating the interactive component of the project, we gained our first experience coding with `html` and `d3` to create a webpage that can take user's input and output corresponding plot of flight delay time. The course and the project not only taught us how to conduct exploratory data analysis and visualization, but also gave us an opportunity to use what we learned in practice. We appreciate it and really enjoy the process.