--- 
title: "Flight Performance Analysis"
author: "Ziyan Liu, Mingyue Xu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We would like to choose the topic related to the flight performance in U.S., more precisely, the time performance (arrival or departure delays) with respect to different settings of airlines, seasons, destinations, departure time, etc. The experience we learned from the observed data will help us make more reasonable decisions in choosing travelling modes, for example, one may be interested in which airline, which airport, when and where is the best combination for travelling from NYC. Such concerns are closely related to daily life and thus the data analysis is of great significance. Concretely, we will investigate the following three problems:

1) Among all the carriers that provide commercial services in U.S., are there any carriers that have major delay problems? For example, the average delay time is over 60 minutes. Indeed, there are different delay reasons such like *CARRIER DELAY*, *WEATHER DELAY*, *AIRCRAFT DELAY*, etc., and airlines may performance differently with respect to a specific delay reason. Furthermore, delay count and delay time are both reasonable measures to the time performance, and should be analyzed respectively, but combined when making decisions.

2) Are early flights or late flights more likely to delay? Do origin and destination influence the on-time performance? Flight performance may be affected by many environmental factors such as seasons, departure time, weather, etc., thus being intricate and hard to analyze. However, visualization can greatly help us in clearing up those relations and variable controlled analysis will assist the decision making in the following problem3.

3) Specifically for NYC. If someone wants to come to NYC, which airport should he/she choose to fly to based on the origin city? Based on the experience we learned from past in problem1 and problem2, more reasonable decisions can be made for travelling from NYC under different factor settings. The goal is to avoid delays and save time, which is helpful in both business travel and leisure travel. 